name: "Postprocess Pages"
on:
  push:
    branches: gh-pages
    paths-ignore: "index.html"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Build
        run: |
          bash postprocess.sh

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: .
